# Generated by Django 5.0.6 on 2024-07-06 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User_Table',
        ),
    ]
